CREATE TABLE `_laender` (
  `code` char(2) CHARACTER SET utf8 NOT NULL PRIMARY KEY,
  `en` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `de` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `es` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `fr` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `it` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `ru` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_german2_ci ROW_FORMAT=DYNAMIC;

INSERT INTO `_laender` (`code`, `en`, `de`, `es`, `fr`, `it`, `ru`) VALUES
('ad', 'Andorra', 'Andorra', 'Andorra', 'ANDORRE', 'Andorra ', 'Андорра'),
('ae', 'United Arab Emirates', 'Vereinigte Arabische Emirate', 'Emiratos Árabes Unidos', 'ÉMIRATS ARABES UNIS', 'Emirati Arabi Uniti ', 'ОАЭ'),
('af', 'Afghanistan', 'Afghanistan', 'Afganistán', 'AFGHANISTAN', 'Afghanistan', 'Афганистан'),
('ag', 'Antigua and Barbuda', 'Antigua und Barbuda', 'Antigua y Barbuda', 'ANTIGUA-ET-BARBUDA', 'Antigua e Barbuda', 'Антигуа и Барбуда'),
('ai', 'Anguilla', 'Anguilla', 'Anguila', 'ANGUILLA', 'Anguilla', 'Ангилья'),
('al', 'Albania', 'Albanien', 'Albania', 'ALBANIE', 'Albania ', 'Албания'),
('am', 'Armenia', 'Armenien', 'Armenia', 'ARMÉNIE', 'Armenia ', 'Армения'),
('an', 'Netherlands Antilles', 'Niederländische Antillen', 'Antillas Neerlandesas', '', '', ''),
('ao', 'Angola', 'Angola', 'Angola', 'ANGOLA', 'Angola ', 'Ангола'),
('aq', 'Antarctica', 'Antarktis', 'Antártida', 'ANTARCTIQUE', 'Antartide ', 'Антарктида'),
('ar', 'Argentina', 'Argentinien', 'Argentina', 'ARGENTINE', 'Argentina ', 'Аргентина'),
('as', 'American Samoa', 'Amerikanisch-Samoa', 'Samoa Americana', 'SAMOA AMÉRICAINES', 'Samoa Americane', 'Американское Самоа'),
('at', 'Austria', 'Österreich', 'Austria', 'AUTRICHE', 'Austria', 'Австрия'),
('au', 'Australia', 'Australien', 'Australia', 'AUSTRALIE', 'Australia', 'Австралия'),
('aw', 'Aruba', 'Aruba', 'Aruba', 'ARUBA', 'Aruba', 'Аруба'),
('ax', 'Aland Islands', 'Åland', 'Islas Áland', 'ÅLAND, ÎLES', 'Isole Åland', 'Аландские острова'),
('az', 'Azerbaijan', 'Aserbaidschan', 'Azerbaiyán', 'AZERBAÏDJAN', 'Azerbaigian', 'Азербайджан'),
('ba', 'Bosnia and Herzegovina', 'Bosnien und Herzegowina', 'Bosnia y Herzegovina', 'BOSNIE-HERZÉGOVINE', 'Bosnia ed Erzegovina', 'Босния и Герцеговина'),
('bb', 'Barbados', 'Barbados', 'Barbados', 'BARBADE', 'Barbados', 'Барбадос'),
('bd', 'Bangladesh', 'Bangladesch', 'Bangladesh', 'BANGLADESH', 'Bangladesh', 'Бангладеш'),
('be', 'Belgium', 'Belgien', 'Bélgica', 'BELGIQUE', 'Belgio', 'Бельгия'),
('bf', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'BURKINA FASO', 'Burkina Faso', 'Буркина-Фасо'),
('bg', 'Bulgaria', 'Bulgarien', 'Bulgaria', 'BULGARIE', 'Bulgaria', 'Болгария'),
('bh', 'Bahrain', 'Bahrain', 'Bahréin', 'BAHREÏN', 'Bahrein', 'Бахрейн'),
('bi', 'Burundi', 'Burundi', 'Burundi', 'BURUNDI', 'Burundi', 'Бурунди'),
('bj', 'Benin', 'Benin', 'Benin', 'BÉNIN', 'Benin', 'Бенин'),
('bl', 'Saint Barthelemy !Saint Barthélemy', 'Saint-Barthélemy', 'Saint Barthélemy', 'SAINT-BARTHÉLEMY', 'Saint-Barthélemy', 'Сен-Бартелеми'),
('bm', 'Bermuda', 'Bermuda', 'Bermudas', 'BERMUDES', 'Bermuda', 'Бермуды'),
('bn', 'Brunei', 'Brunei Darussalam', 'Brunéi', 'BRUNÉI DARUSSALAM', 'Brunei', 'Бруней'),
('bo', 'Bolivia', 'Bolivien', 'Bolivia', 'BOLIVIE, ÉTAT PLURINATIONAL DE', 'Bolivia', 'Боливия'),
('bq', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius und Saba', 'Bonaire, San Eustaquio y Saba', 'BONAIRE, SAINT-EUSTACHE ET SABA', 'Isole BES', 'Синт-Эстатиус и Саба'),
('br', 'Brazil', 'Brasilien', 'Brasil', 'BRÉSIL', 'Brasile', 'Бразилия'),
('bs', 'Bahamas', 'Bahamas', 'Bahamas', 'BAHAMAS', 'Bahamas', 'Багамы'),
('bt', 'Bhutan', 'Bhutan', 'Bhután', 'BHOUTAN', 'Bhutan', 'Бутан'),
('bv', 'Bouvet Island', 'Bouvetinsel', 'Isla Bouvet', 'BOUVET, ÎLE', 'Isola Bouvet', 'Остров Буве'),
('bw', 'Botswana', 'Botswana', 'Botsuana', 'BOTSWANA', 'Botswana', 'Ботсвана'),
('by', 'Belarus', 'Belarus (Weißrussland)', 'Belarús', 'BÉLARUS', 'Bielorussia', 'Белоруссия'),
('bz', 'Belize', 'Belize', 'Belice', 'BELIZE', 'Belize', 'Белиз'),
('ca', 'Canada', 'Kanada', 'Canadá', 'CANADA', 'Canada', 'Канада'),
('cc', 'Cocos (Keeling) Islands', 'Kokosinseln (Keelinginseln)', 'Islas Cocos', 'COCOS (KEELING), ÎLES', 'Isole Cocos (Keeling)', 'Кокосовые острова'),
('cd', 'Congo (Kinshasa)', 'Kongo', 'Congo', 'CONGO, LA RÉPUBLIQUE DÉMOCRATIQUE DU', 'RD del Congo', 'Демократическая Республика Конго'),
('cf', 'Central African Republic', 'Zentralafrikanische Republik', 'República Centro-Africana', 'CENTRAFRICAINE, RÉPUBLIQUE', 'Rep. Centrafricana', 'ЦАР'),
('cg', 'Congo (Brazzaville)', 'Republik Kongo', 'Congo', 'CONGO', 'Rep. del Congo', 'Республика Конго'),
('ch', 'Switzerland', 'Schweiz', 'Suiza', 'SUISSE', 'Svizzera', 'Швейцария'),
('ci', 'Ivory Coast', 'Elfenbeinküste', 'Costa de Marfil', 'CÔTE D’IVOIRE', 'Costa d\'Avorio', 'Кот-д’Ивуар'),
('ck', 'Cook Islands', 'Cookinseln', 'Islas Cook', 'COOK, ÎLES', 'Isole Cook', 'Острова Кука'),
('cl', 'Chile', 'Chile', 'Chile', 'CHILI', 'Cile', 'Чили'),
('cm', 'Cameroon', 'Kamerun', 'Camerún', 'CAMEROUN', 'Camerun', 'Камерун'),
('cn', 'China', 'China, Volksrepublik', 'China', 'CHINE', 'Cina', 'КНР (Китайская Народная Республика)'),
('co', 'Colombia', 'Kolumbien', 'Colombia', 'COLOMBIE', 'Colombia', 'Колумбия'),
('cr', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'COSTA RICA', 'Costa Rica', 'Коста-Рика'),
('cu', 'Cuba', 'Kuba', 'Cuba', 'CUBA', 'Cuba', 'Куба'),
('cv', 'Cape Verde', 'Kap Verde', 'Cabo Verde', 'CABO VERDE', 'Capo Verde', 'Кабо-Верде'),
('cw', 'Curacao !Curaçao', 'Curaçao', 'Curaçao', 'CURAÇAO', 'Curaçao', 'Кюрасао'),
('cx', 'Christmas Island', 'Weihnachtsinsel', 'Islas Christmas', 'CHRISTMAS, ÎLE', 'Isola di Natale', 'Остров Рождества'),
('cy', 'Cyprus', 'Zypern', 'Chipre', 'CHYPRE', 'Cipro', 'Кипр'),
('cz', 'Czech Republic', 'Tschechische Republik', 'República Checa', 'TCHÈQUE, RÉPUBLIQUE', 'Rep. Ceca', 'Чехия'),
('de', 'Germany', 'Deutschland', 'Alemania', 'ALLEMAGNE', 'Germania', 'Германия'),
('dj', 'Djibouti', 'Dschibuti', 'Yibuti', 'DJIBOUTI', 'Gibuti', 'Джибути'),
('dk', 'Denmark', 'Dänemark', 'Dinamarca', 'DANEMARK', 'Danimarca', 'Дания'),
('dm', 'Dominica', 'Dominica', 'Domínica', 'DOMINIQUE', 'Dominica', 'Доминика'),
('do', 'Dominican Republic', 'Dominikanische Republik', 'República Dominicana', 'DOMINICAINE, RÉPUBLIQUE', 'Rep. Dominicana', 'Доминиканская Республика'),
('dz', 'Algeria', 'Algerien', 'Argelia', 'ALGÉRIE', 'Algeria', 'Алжир'),
('ec', 'Ecuador', 'Ecuador', 'Ecuador', 'ÉQUATEUR', 'Ecuador', 'Эквадор'),
('ee', 'Estonia', 'Estland (Reval)', 'Estonia', 'ESTONIE', 'Estonia', 'Эстония'),
('eg', 'Egypt', 'Ägypten', 'Egipto', 'ÉGYPTE', 'Egitto', 'Египет'),
('eh', 'Western Sahara', 'Westsahara', 'Sahara Occidental', 'SAHARA OCCIDENTAL', 'Sahara Occidentale', 'САДР'),
('er', 'Eritrea', 'Eritrea', 'Eritrea', 'ÉRYTHRÉE', 'Eritrea', 'Эритрея'),
('es', 'Spain', 'Spanien', 'España', 'ESPAGNE', 'Spagna', 'Испания'),
('et', 'Ethiopia', 'Äthiopien', 'Etiopía', 'ÉTHIOPIE', 'Etiopia', 'Эфиопия'),
('fi', 'Finland', 'Finnland', 'Finlandia', 'FINLANDE', 'Finlandia', 'Финляндия'),
('fj', 'Fiji', 'Fidschi', 'Fiji', 'FIDJI', 'Figi', 'Фиджи'),
('fk', 'Falkland Islands', 'Falklandinseln (Malwinen)', 'Islas Malvinas', 'FALKLAND, ÎLES (MALVINAS)', 'Isole Falkland', 'Фолклендские острова'),
('fm', 'Micronesia', 'Mikronesien', 'Micronesia', 'MICRONÉSIE, ÉTATS FÉDÉRÉS DE', 'Micronesia', 'Микронезия'),
('fo', 'Faroe Islands', 'Färöer', 'Islas Faroe', 'FÉROÉ, ÎLES', 'Fær Øer', 'Фареры'),
('fr', 'France', 'Frankreich', 'Francia', 'FRANCE', 'Francia', 'Франция'),
('ga', 'Gabon', 'Gabun', 'Gabón', 'GABON', 'Gabon', 'Габон'),
('gb', 'United Kingdom', 'Großbritannien und Nordirland', 'Reino Unido', 'ROYAUME-UNI', 'Regno Unito', 'Великобритания'),
('gd', 'Grenada', 'Grenada', 'Granada', 'GRENADE', 'Grenada', 'Гренада'),
('ge', 'Georgia', 'Georgien', 'Georgia', 'GÉORGIE', 'Georgia', 'Грузия'),
('gf', 'French Guiana', 'Französisch-Guayana', 'Guayana Francesa', 'GUYANE FRANÇAISE', 'Guyana francese', 'Гвиана'),
('gg', 'Guernsey', 'Guernsey (Kanalinsel)', 'Guernsey', 'GUERNESEY', 'Guernsey', 'Гернси'),
('gh', 'Ghana', 'Ghana', 'Ghana', 'GHANA', 'Ghana', 'Гана'),
('gi', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'GIBRALTAR', 'Gibilterra', 'Гибралтар'),
('gl', 'Greenland', 'Grönland', 'Groenlandia', 'GROENLAND', 'Groenlandia', 'Гренландия'),
('gm', 'Gambia', 'Gambia', 'Gambia', 'GAMBIE', 'Gambia', 'Гамбия'),
('gn', 'Guinea', 'Guinea', 'Guinea', 'GUINÉE', 'Guinea', 'Гвинея'),
('gp', 'Guadeloupe', 'Guadeloupe', 'Guadalupe', 'GUADELOUPE', 'Guadalupa', 'Гваделупа'),
('gq', 'Equatorial Guinea', 'Äquatorialguinea', 'Guinea Ecuatorial', 'GUINÉE ÉQUATORIALE', 'Guinea Equatoriale', 'Экваториальная Гвинея'),
('gr', 'Greece', 'Griechenland', 'Grecia', 'GRÈCE', 'Grecia ', 'Греция'),
('gs', 'South Georgia and the South Sandwich Islands', 'Südgeorgien und die Südl. Sandwichinseln', 'Georgia del Sur e Islas Sandwich del Sur', 'GÉORGIE DU SUD ET LES ÎLES SANDWICH DU SUD', 'Georgia del Sud e isole Sandwich meridionali', 'Южная Георгия и Южные Сандвичевы Острова'),
('gt', 'Guatemala', 'Guatemala', 'Guatemala', 'GUATEMALA', 'Guatemala', 'Гватемала'),
('gu', 'Guam', 'Guam', 'Guam', 'GUAM', 'Guam', 'Гуам'),
('gw', 'Guinea-Bissau', 'Guinea-Bissau', 'Guinea-Bissau', 'GUINÉE-BISSAU', 'Guinea-Bissau', 'Гвинея-Бисау'),
('gy', 'Guyana', 'Guyana', 'Guayana', 'GUYANA', 'Guyana', 'Гайана'),
('hk', 'Hong Kong S.A.R., China', 'Hongkong', 'Hong Kong', 'HONG KONG', 'Hong Kong', 'Гонконг'),
('hm', 'Heard Island and McDonald Islands', 'Heard- und McDonald-Inseln', 'Islas Heard y McDonald', 'HEARD ET MACDONALD, ÎLES', 'Isole Heard e McDonald', 'Херд и Макдональд'),
('hn', 'Honduras', 'Honduras', 'Honduras', 'HONDURAS', 'Honduras', 'Гондурас'),
('hr', 'Croatia', 'Kroatien', 'Croacia', 'CROATIE', 'Croazia', 'Хорватия'),
('ht', 'Haiti', 'Haiti', 'Haití', 'HAÏTI', 'Haiti ', 'Гаити'),
('hu', 'Hungary', 'Ungarn', 'Hungría', 'HONGRIE', 'Ungheria', 'Венгрия'),
('id', 'Indonesia', 'Indonesien', 'Indonesia', 'INDONÉSIE', 'Indonesia', 'Индонезия'),
('ie', 'Ireland', 'Irland', 'Irlanda', 'IRLANDE', 'Irlanda ', 'Флаг Ирландии Ирландия'),
('il', 'Israel', 'Israel', 'Israel', 'ISRAËL', 'Israele ', 'Израиль'),
('im', 'Isle of Man', 'Insel Man', 'Isla de Man', 'ÎLE DE MAN', 'Isola di Man', 'Остров Мэн'),
('in', 'India', 'Indien', 'India', 'INDE', 'India ', 'Индия Индия'),
('io', 'British Indian Ocean Territory', 'Britisches Territorium im Indischen Ozean', 'Territorio Británico del Océano Índico', 'OCÉAN INDIEN, TERRITOIRE BRITANNIQUE DE L\'', 'Territorio britannico dell\'oceano', 'Британская территория в Индийском океане'),
('iq', 'Iraq', 'Irak', 'Irak', 'IRAQ', 'Iraq ', 'Ирак'),
('ir', 'Iran', 'Iran', 'Irán', 'IRAN, RÉPUBLIQUE ISLAMIQUE D\'', 'Iran ', 'Иран'),
('is', 'Iceland', 'Island', 'Islandia', 'ISLANDE', 'Islanda ', 'Исландия'),
('it', 'Italy', 'Italien', 'Italia', 'ITALIE', 'Italia ', 'Италия'),
('je', 'Jersey', 'Jersey (Kanalinsel)', 'Jersey', 'JERSEY', 'Jersey ', 'Джерси'),
('jm', 'Jamaica', 'Jamaika', 'Jamaica', 'JAMAÏQUE', 'Giamaica', 'Ямайка'),
('jo', 'Jordan', 'Jordanien', 'Jordania', 'JORDANIE', 'Giordania ', 'Иордания'),
('jp', 'Japan', 'Japan', 'Japón', 'JAPON', 'Giappone ', 'Япония'),
('ke', 'Kenya', 'Kenia', 'Kenia', 'KENYA', 'Kenya ', 'Кения'),
('kg', 'Kyrgyzstan', 'Kirgisistan', 'Kirguistán', 'KIRGHIZISTAN', 'Kirghizistan', 'Киргизия'),
('kh', 'Cambodia', 'Kambodscha', 'Camboya', 'CAMBODGE', 'Cambogia ', 'Камбоджа'),
('ki', 'Kiribati', 'Kiribati', 'Kiribati', 'KIRIBATI', 'Kiribati ', 'Кирибати'),
('km', 'Comoros', 'Komoren', 'Comoros', 'COMORES', 'Comore ', 'Коморы'),
('kn', 'Saint Kitts and Nevis', 'St. Kitts und Nevis', 'San Cristóbal y Nieves', 'SAINT-KITTS-ET-NEVIS', 'Saint Kitts e Nevis', 'Сент-Китс и Невис'),
('kp', 'North Korea', 'Nordkorea', 'Corea del Norte', 'CORÉE, RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE', 'Corea del Nord ', 'КНДР (Корейская Народно-Демократическая Республика)'),
('kr', 'South Korea', 'Südkorea', 'Corea del Sur', 'CORÉE, RÉPUBLIQUE DE', 'Corea del Sud ', 'Республика Корея'),
('kw', 'Kuwait', 'Kuwait', 'Kuwait', 'KOWEÏT', 'Kuwait ', 'Кувейт'),
('ky', 'Cayman Islands', 'Kaimaninseln', 'Islas Caimán', 'CAÏMANES, ÎLES', 'Isole Cayman', 'Острова Кайман'),
('kz', 'Kazakhstan', 'Kasachstan', 'Kazajstán', 'KAZAKHSTAN', 'Kazakistan ', 'Казахстан'),
('la', 'Laos', 'Laos', 'Laos', 'LAO, RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE', 'Laos ', 'Лаос'),
('lb', 'Lebanon', 'Libanon', 'Líbano', 'LIBAN', 'Libano', 'Ливан'),
('lc', 'Saint Lucia', 'St. Lucia', 'Santa Lucía', 'SAINTE-LUCIE', 'Santa Lucia', 'Сент-Люсия'),
('li', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'LIECHTENSTEIN', 'Liechtenstein', 'Лихтенштейн'),
('lk', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'SRI LANKA', 'Sri Lanka ', 'Шри-Ланка'),
('lr', 'Liberia', 'Liberia', 'Liberia', 'LIBÉRIA', 'Liberia ', 'Либерия'),
('ls', 'Lesotho', 'Lesotho', 'Lesotho', 'LESOTHO', 'Lesotho ', 'Лесото'),
('lt', 'Lithuania', 'Litauen', 'Lituania', 'LITUANIE', 'Lituania', 'Литва'),
('lu', 'Luxembourg', 'Luxemburg', 'Luxemburgo', 'LUXEMBOURG', 'Lussemburgo', 'Люксембург'),
('lv', 'Latvia', 'Lettland', 'Letonia', 'LETTONIE', 'Lettonia ', 'Латвия'),
('ly', 'Libya', 'Libyen', 'Libia', 'LIBYE', 'Libia ', 'Ливия'),
('ma', 'Morocco', 'Marokko', 'Marruecos', 'MAROC', 'Marocco', 'Марокко'),
('mc', 'Monaco', 'Monaco', 'Mónaco', 'MONACO', 'Monaco ', 'Монако'),
('md', 'Moldova', 'Moldawien', 'Moldova', 'MOLDOVA', 'Moldavia', 'Молдавия'),
('me', 'Montenegro', 'Montenegro', 'Montenegro', 'MONTÉNÉGRO', 'Montenegro', 'Черногория'),
('mf', 'Saint Martin (French part)', 'Saint-Martin (franz. Teil)', 'Saint Martin (parte francesa)', 'SAINT-MARTIN (PARTIE FRANÇAISE)', 'Saint-Martin', 'Сен-Мартен'),
('mg', 'Madagascar', 'Madagaskar', 'Madagascar', 'MADAGASCAR', 'Madagascar ', 'Мадагаскар'),
('mh', 'Marshall Islands', 'Marshallinseln', 'Islas Marshall', 'MARSHALL, ÎLES', 'Isole Marshall', 'Маршалловы Острова'),
('mk', 'Macedonia', 'Mazedonien', 'Macedonia', 'MACÉDOINE, L\'EX-RÉPUBLIQUE YOUGOSLAVE DE', 'Macedonia ', 'Македония'),
('ml', 'Mali', 'Mali', 'Mali', 'MALI', 'Mali ', 'Мали'),
('mm', 'Myanmar', 'Myanmar (Burma)', 'Myanmar', 'MYANMAR', 'Birmania', 'Мьянма'),
('mn', 'Mongolia', 'Mongolei', 'Mongolia', 'MONGOLIE', 'Mongolia', 'Монголия'),
('mo', 'Macao S.A.R., China', 'Macau', 'Macao', 'MACAO', 'Macao ', 'Макао'),
('mp', 'Northern Mariana Islands', 'Nördliche Marianen', 'Islas Marianas del Norte', 'MARIANNES DU NORD, ÎLES', 'Isole Marianne Settentrionali', 'Северные Марианские острова'),
('mq', 'Martinique', 'Martinique', 'Martinica', 'MARTINIQUE', 'Martinica', 'Мартиника'),
('mr', 'Mauritania', 'Mauretanien', 'Mauritania', 'MAURITANIE', 'Mauritania', 'Мавритания'),
('ms', 'Montserrat', 'Montserrat', 'Montserrat', 'MONTSERRAT', 'Montserrat', 'Монтсеррат'),
('mt', 'Malta', 'Malta', 'Malta', 'MALTE', 'Malta ', 'Мальта'),
('mu', 'Mauritius', 'Mauritius', 'Mauricio', 'MAURICE', 'Mauritius', 'Маврикий'),
('mv', 'Maldives', 'Malediven', 'Maldivas', 'MALDIVES', 'Maldive ', 'Мальдивы'),
('mw', 'Malawi', 'Malawi', 'Malawi', 'MALAWI', 'Malawi ', 'Малави'),
('mx', 'Mexico', 'Mexiko', 'México', 'MEXIQUE', 'Messico ', 'Мексика'),
('my', 'Malaysia', 'Malaysia', 'Malasia', 'MALAISIE', 'Malesia ', 'Малайзия'),
('mz', 'Mozambique', 'Mosambik', 'Mozambique', 'MOZAMBIQUE', 'Mozambico', 'Мозамбик'),
('na', 'Namibia', 'Namibia', 'Namibia', 'NAMIBIE', 'Namibia ', 'Намибия'),
('nc', 'New Caledonia', 'Neukaledonien', 'Nueva Caledonia', 'NOUVELLE-CALÉDONIE', 'Nuova Caledonia', 'Новая Каледония'),
('ne', 'Niger', 'Niger', 'Níger', 'NIGER', 'Niger ', 'Нигер'),
('nf', 'Norfolk Island', 'Norfolkinsel', 'Islas Norkfolk', 'NORFOLK, ÎLE', 'Isola Norfolk', 'Остров Норфолк'),
('ng', 'Nigeria', 'Nigeria', 'Nigeria', 'NIGÉRIA', 'Nigeria ', 'Нигерия'),
('ni', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'NICARAGUA', 'Nicaragua', 'Никарагуа'),
('nl', 'Netherlands', 'Niederlande', 'Países Bajos', 'PAYS-BAS', 'Paesi Bassi', 'Нидерланды'),
('no', 'Norway', 'Norwegen', 'Noruega', 'NORVÈGE', 'Norvegia ', 'Норвегия'),
('np', 'Nepal', 'Nepal', 'Nepal', 'NÉPAL', 'Nepal ', 'Непал'),
('nr', 'Nauru', 'Nauru', 'Nauru', 'NAURU', 'Nauru ', 'Науру'),
('nu', 'Niue', 'Niue', 'Niue', 'NIUÉ', 'Niue ', 'Ниуэ'),
('nz', 'New Zealand', 'Neuseeland', 'Nueva Zelanda', 'NOUVELLE-ZÉLANDE', 'Nuova Zelanda', 'Новая Зеландия'),
('om', 'Oman', 'Oman', 'Omán', 'OMAN', 'Oman ', 'Оман'),
('pa', 'Panama', 'Panama', 'Panamá', 'PANAMA', 'Panamá', 'Панама'),
('pe', 'Peru', 'Peru', 'Perú', 'PÉROU', 'Perù ', 'Перу'),
('pf', 'French Polynesia', 'Französisch-Polynesien', 'Polinesia Francesa', 'POLYNÉSIE FRANÇAISE', 'Polinesia Francese ', 'Французская Полинезия'),
('pg', 'Papua New Guinea', 'Papua-Neuguinea', 'Papúa Nueva Guinea', 'PAPOUASIE-NOUVELLE-GUINÉE', 'Papua Nuova Guinea ', 'Папуа — Новая Гвинея'),
('ph', 'Philippines', 'Philippinen', 'Filipinas', 'PHILIPPINES', 'Filippine ', 'Филиппины'),
('pk', 'Pakistan', 'Pakistan', 'Pakistán', 'PAKISTAN', 'Pakistan ', 'Пакистан'),
('pl', 'Poland', 'Polen', 'Polonia', 'POLOGNE', 'Polonia ', 'Польша'),
('pm', 'Saint Pierre and Miquelon', 'St. Pierre und Miquelon', 'San Pedro y Miquelón', 'SAINT-PIERRE-ET-MIQUELON', 'Saint-Pierre e Miquelon', 'Сен-Пьер и Микелон'),
('pn', 'Pitcairn', 'Pitcairninseln', 'Islas Pitcairn', 'PITCAIRN', 'Isole Pitcairn ', 'Острова Питкэрн'),
('pr', 'Puerto Rico', 'Puerto Rico', 'Puerto Rico', 'PORTO RICO', 'Porto Rico ', 'Пуэрто-Рико'),
('ps', 'Palestine', 'Palästina', 'Palestina', 'ÉTAT DE PALESTINE', 'Palestina ', 'Государство Палестина'),
('pt', 'Portugal', 'Portugal', 'Portugal', 'PORTUGAL', 'Portogallo ', 'Португалия'),
('pw', 'Palau', 'Palau', 'Islas Palaos', 'PALAOS', 'Palau ', 'Палау'),
('py', 'Paraguay', 'Paraguay', 'Paraguay', 'PARAGUAY', 'Paraguay ', 'Парагвай'),
('qa', 'Qatar', 'Katar', 'Qatar', 'QATAR', 'Qatar ', 'Катар'),
('re', 'Reunion', 'Réunion', 'Reunión', 'RÉUNION', 'Riunione ', 'Реюньон'),
('ro', 'Romania', 'Rumänien', 'Rumanía', 'ROUMANIE', 'Romania ', 'Румыния'),
('rs', 'Serbia', 'Serbien', 'Serbia', 'SERBIE', 'Serbia ', 'Сербия'),
('ru', 'Russia', 'Russische Föderation', 'Rusia', 'RUSSIE, FÉDÉRATION DE', 'Russia ', 'Россия'),
('rw', 'Rwanda', 'Ruanda', 'Ruanda', 'RWANDA', 'Ruanda ', 'Руанда'),
('sa', 'Saudi Arabia', 'Saudi-Arabien', 'Arabia Saudita', 'ARABIE SAOUDITE', 'Arabia Saudita', 'Саудовская Аравия'),
('sb', 'Solomon Islands', 'Salomonen', 'Islas Solomón', 'SALOMON, ÎLES', 'Isole Salomone', 'Соломоновы Острова'),
('sc', 'Seychelles', 'Seychellen', 'Seychelles', 'SEYCHELLES', 'Seychelles', 'Сейшельские Острова'),
('sd', 'Sudan', 'Sudan', 'Sudán', 'SOUDAN', 'Sudan ', 'Судан'),
('se', 'Sweden', 'Schweden', 'Suecia', 'SUÈDE', 'Svezia', 'Швеция'),
('sg', 'Singapore', 'Singapur', 'Singapur', 'SINGAPOUR', 'Singapore', 'Сингапур'),
('sh', 'Saint Helena', 'St. Helena', 'Santa Elena', 'SAINTE-HÉLÈNE, ASCENSION ET TRISTAN DA CUNHA', 'Sant\'Elena, Ascensione e Tristan da Cunha', 'Острова Святой Елены, Вознесения и Тристан-да-Кунья'),
('si', 'Slovenia', 'Slowenien', 'Eslovenia', 'SLOVÉNIE', 'Slovenia Slovenia', 'Словения'),
('sj', 'Svalbard and Jan Mayen', 'Svalbard und Jan Mayen', 'Islas Svalbard y Jan Mayen', 'SVALBARD ET ÎLE JAN MAYEN', 'Svalbard e Jan Mayen', 'Флаг Шпицбергена и Ян-Майена Шпицберген и Ян-Майен'),
('sk', 'Slovakia', 'Slowakei', 'Eslovaquia', 'SLOVAQUIE', 'Slovacchia ', 'Словакия'),
('sl', 'Sierra Leone', 'Sierra Leone', 'Sierra Leona', 'SIERRA LEONE', 'Sierra Leone', 'Сьерра-Леоне'),
('sm', 'San Marino', 'San Marino', 'San Marino', 'SAINT-MARIN', 'San Marino ', 'Сан-Марино'),
('sn', 'Senegal', 'Senegal', 'Senegal', 'SÉNÉGAL', 'Senegal ', 'Сенегал'),
('so', 'Somalia', 'Somalia', 'Somalia', 'SOMALIE', 'Somalia ', 'Сомали'),
('sr', 'Suriname', 'Suriname', 'Surinam', 'SURINAME', 'Suriname', 'Суринам'),
('ss', 'South Sudan', 'Sudsudan!Südsudan', 'Sudán del Sur', 'SOUDAN DU SUD', 'Sudan del Sud', 'Южный Судан'),
('st', 'Sao Tome and Principe', 'São Tomé und Príncipe', 'Santo Tomé y Príncipe', 'SAO TOMÉ-ET-PRINCIPE', 'São Tomé e Príncipe', 'Сан-Томе и Принсипи'),
('sv', 'El Salvador', 'El Salvador', 'El Salvador', 'EL SALVADOR', 'El Salvador ', 'Сальвадор'),
('sx', 'Sint Maarten (Dutch part)', 'Sint Maarten (niederl. Teil)', 'Sint Maarten (parte neerlandesa)', 'SAINT-MARTIN (PARTIE NÉERLANDAISE)', 'Sint Maarten ', 'Синт-Мартен'),
('sy', 'Syria', 'Syrien', 'Siria', 'SYRIENNE, RÉPUBLIQUE ARABE', 'Siria ', 'Сирия'),
('sz', 'Swaziland', 'Swasiland', 'Suazilandia', 'SWAZILAND', 'Swaziland', 'Свазиленд'),
('tc', 'Turks and Caicos Islands', 'Turks- und Caicosinseln', 'Islas Turcas y Caicos', 'TURKS ET CAÏQUES, ÎLES', 'Turks e Caicos ', 'Тёркс и Кайкос'),
('td', 'Chad', 'Tschad', 'Chad', 'TCHAD', 'Ciad ', 'Чад'),
('tf', 'French Southern Territories', 'Französische Süd- und Antarktisgebiete', 'Territorios Australes Franceses', 'TERRES AUSTRALES FRANÇAISES', 'Terre australi e antartiche francesi', 'Французские Южные и Антарктические Территории'),
('tg', 'Togo', 'Togo', 'Togo', 'TOGO', 'Togo ', 'Того'),
('th', 'Thailand', 'Thailand', 'Tailandia', 'THAÏLANDE', 'Thailandia', 'Таиланд'),
('tj', 'Tajikistan', 'Tadschikistan', 'Tayikistán', 'TADJIKISTAN', 'Tagikistan', 'Таджикистан'),
('tk', 'Tokelau', 'Tokelau', 'Tokelau', 'TOKELAU', 'Tokelau ', 'Токелау'),
('tl', 'East Timor', 'Timor-Leste', 'Timor-Leste', 'TIMOR-LESTE', 'Timor Est', 'Восточный Тимор'),
('tm', 'Turkmenistan', 'Turkmenistan', 'Turkmenistán', 'TURKMÉNISTAN', 'Turkmenistan', 'Туркмения'),
('tn', 'Tunisia', 'Tunesien', 'Túnez', 'TUNISIE', 'Tunisia ', 'Тунис'),
('to', 'Tonga', 'Tonga', 'Tonga', 'TONGA', 'Tonga ', 'Тонга'),
('tr', 'Turkey', 'Türkei', 'Turquía', 'TURQUIE', 'Turchia', 'Турция'),
('tt', 'Trinidad and Tobago', 'Trinidad und Tobago', 'Trinidad y Tobago', 'TRINITÉ-ET-TOBAGO', 'Trinidad e Tobago', 'Тринидад и Тобаго'),
('tv', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'TUVALU', 'Tuvalu ', 'Тувалу'),
('tw', 'Taiwan', 'Taiwan', 'Taiwán', 'TAÏWAN, PROVINCE DE CHINE', 'Taiwan ', 'Китайская Республика'),
('tz', 'Tanzania', 'Tansania', 'Tanzania', 'TANZANIE, RÉPUBLIQUE UNIE DE', 'Tanzania ', 'Танзания'),
('ua', 'Ukraine', 'Ukraine', 'Ucrania', 'UKRAINE', 'Ucraina ', 'Украина'),
('ug', 'Uganda', 'Uganda', 'Uganda', 'OUGANDA', 'Uganda ', 'Уганда'),
('um', 'United States Minor Outlying Islands', 'Amerikanisch-Ozeanien', 'Islas menores periféricas de los Estados Unidos', 'ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS', 'Isole minori esterne degli Stati Uniti', 'Внешние малые острова (США)'),
('us', 'United States', 'Vereinigte Staaten von Amerika', 'Estados Unidos de América', 'ÉTATS-UNIS', 'Stati Uniti', 'США'),
('uy', 'Uruguay', 'Uruguay', 'Uruguay', 'URUGUAY', 'Uruguay ', 'Уругвай'),
('uz', 'Uzbekistan', 'Usbekistan', 'Uzbekistán', 'OUZBÉKISTAN', 'Uzbekistan', 'Узбекистан'),
('va', 'Vatican', 'Vatikanstadt', 'Ciudad del Vaticano', 'SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN)', 'Città del Vaticano', 'Ватикан'),
('vc', 'Saint Vincent and the Grenadines', 'St. Vincent und die Grenadinen', 'San Vicente y las Granadinas', 'SAINT-VINCENT-ET-LES-GRENADINES', 'Saint Vincent e Grenadine', 'Сент-Винсент и Гренадины'),
('ve', 'Venezuela', 'Venezuela', 'Venezuela', 'VENEZUELA, RÉPUBLIQUE BOLIVARIENNE DU', 'Venezuela ', 'Венесуэла'),
('vg', 'British Virgin Islands', 'Britische Jungferninseln', 'Islas Vírgenes Británicas', 'ÎLES VIERGES BRITANNIQUES', 'Isole Vergini britanniche ', 'Британские Виргинские острова'),
('vi', 'U.S. Virgin Islands', 'Amerikanische Jungferninseln', 'Islas Vírgenes de los Estados Unidos de América', 'ÎLES VIERGES DES ÉTATS-UNIS', 'Isole Vergini americane ', 'Виргинские Острова (США)'),
('vn', 'Vietnam', 'Vietnam', 'Vietnam', 'VIET NAM', 'Vietnam', 'Вьетнам'),
('vu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'VANUATU', 'Vanuatu', 'Вануату'),
('wf', 'Wallis and Futuna', 'Wallis und Futuna', 'Wallis y Futuna', 'WALLIS-ET-FUTUNA', 'Wallis e Futuna', 'Уоллис и Футуна'),
('ws', 'Samoa', 'Samoa', 'Samoa', 'SAMOA', 'Samoa ', 'Самоа'),
('ye', 'Yemen', 'Jemen', 'Yemen', 'YÉMEN', 'Yemen ', 'Йемен'),
('yt', 'Mayotte', 'Mayotte', 'Mayotte', 'MAYOTTE', 'Mayotte ', 'Майотта'),
('za', 'South Africa', 'Südafrika', 'Sudáfrica', 'AFRIQUE DU SUD', 'Sudafrica ', 'ЮАР'),
('zm', 'Zambia', 'Sambia', 'Zambia', 'ZAMBIE', 'Zambia ', 'Замбия'),
('zw', 'Zimbabwe', 'Simbabwe', 'Zimbabue', 'ZIMBABWE', 'Zimbabwe', 'Зимбабве');
